def Gustavo_choises():
    print('\nSeu nome é Gustavo você tem 22 anos e entrou agora no curso de Psicologia na Universidade De Ottawa no Canada. Você chegou da sua cidade natal - Campina Grande - a pouco tempo e ainda não se acostumou com o clima Norte Americano. Seu dormitório é maravilhoso e tudo que você sempre sonhou.\nNo seu primeiro dia de aula você se arruma todo e corre para não se atrasar, mas há um problema, você não tem a menor ideia para que direção fica sua sala, você para em frente aos portões e não sabe aonde ir!!\n')
    esc = input('Voce tem que decidir pra onde ir, o que voce escolhe?\n1)Em frente\n2)Voltar\nResposta: ')

    if esc == '1':
        print('\nVocê segue em frente por uma estrada de tijolos brancos rodeada de enormes prédios de arquitetura clássica. Durante seu passeio você encontra um grupo de jovens.')
        esc1 = input('O que você faz?\n1)Vai lá e conversa com eles\n2)Segue reto pois não gosta de falar com estranhos\nResposta: ')
        
        if esc1 == '1':
            print('\nVocê se aproxima desse grupo e descobre que eles também fazem Psicologia, e uma moça em especial te chama a atenção.')
            esc2 = input('\nO que você faz em seguida? \n1)Você se apresenta e procura saber o nome de todos\n2)Você conta uma piada e tenta descontrair antes de falar alguma coisa\nResposta: ')

            if esc2 == '1': 
                print('\nVocê percebe que todos os olhares se voltam para você, e aquele moça em especial te esquadrinha por completo.\nApós 10 minutos de fala, você já sabe o nome das três pessoas que estavam lá:\Arthur,Maikon e Susan.\Arthur não era nada especial:tinha olhos castanhos, de pele caucasiana e era menor do que Maikon.\Maikon tinha um ar ameaçador: aparentava ser ucraniano, com uma pele branca e fina e longos cabelos cor de palha.\Susan na sua opnião era bela(se não muito bela): possuia uma aparencia serena, era calma , e nao falava muito , mas nos poucos segundos que esteve com ela , voce foi consumido pela sua calma.')
                esc3 = input('Susan então te olha de cima a baixo e se oferece a te ajudar a encontrar a sua sala.\nVocê aceita?\n1)Sim\n2)Não\nResposta: ')
                
                if esc3 == '1':
                    print('\nVocê e Susan então se despedem dos seus mais novos amigos e partem em direção na busca de sua sala\n')
                    esc4 = input('Voces caminham por mais 5 minutos e então chegam em frente a uma porta onde está escrito: Departamento de Psicologia 101. Voce se volta para Susan com a intenção de agradecê-la e então voce tropeça e cai sobre susan , e os dois caem em frente a sala em uma poziçao relativamente erotica aos olhos dos mais pevertidos(estilo anime ) .O que voce faz?\n1)fica olhando para ela com cara de tacho.\n2)O afasta e entra correndo pra dentro sala.\nResposta: ')
                    
                    if esc4 == '1':
                        print('\nAo cais no chão sua vergonha é tao grande que voce fica em cima dela , a olhando com uma cara de quem sua mãe acabou de dizer para a sala inteira que voce faz xixi na cama. sua vergonha é tao grande que voce , perde noçao de tempo e espaço , voce pode ver que a cara dela se tornou tao vermelha que poderia se compara a vermelhidao da bandeira da china\nA porta estava entreaberta e o seu evento se torna conhecido por toda a sala , um momento de silencio... e então a sala se preenche com os risos, ao olhar para cima voce percebe seu professor lhe olhando friamente.\n')
                        esc5 = input("O que voce faz?\n1)sai de cima de Susan e sai e corre para se sentar no fundo da classe olhando para baixo.\n2)Se levanta rapidamente enquanto ajuda susan a se levantar e pede desculpas a turma e ao professor.\nResposta: ")

                        if esc5 == '1':
                            print("\nVoce passa o resto da aula de cabeça baixa querendo morrer e não consegue prestar atenção em nada, até que as duas eternas horas passam e voce se levanta após todos os seus colegas sairem da sala. Decidida a não passar mais vergonha, voce caminha para suas próximas aulas do dia.\nO dia passa e voce volta para o dormitorio totalmente derrotado, no meio do caminho voce ve de longe aquelas pessoas que voce conheceu mais cedo.\n")
                            esc6 = input('O que voce faz?\n1)Vai falar com eles.\n2)Finge que não os viu e vai direto para o quarto.\nResposta: ')
                            if esc6 == '1':
                                print('\nMesmo tomada de vergonha voce vai falar com Arthur, Maikon e Susan. Ao chegar mais perto percebe que eles estão rindo de algo e voce escuta seu nome.\n')
                                esc7 = input('O que voce faz? \n1)Dá meia volta e desiste de falar.\n2)Se aproxima e pergunta do que eles estão falando.\nResposta: ')
                                
                                if esc7 == '1':
                                    print('\nAo ouvir seu nome voce pressupõe que eles estão falando do seu vergonhoso ato que cometeu com Susan, e com toda razão voce pensou pois era ela que estava falando enquanto todos os outros apenas riam da situação. Voce dá meia volta e corre para seu dormitório, mas não rápido o suficiente para que o grupo risonho não percebesse sua presença. Eles gritam seu nome, mas voce continua correndo.\n\nAo chegar no seu dormitorio voce joga seu material em uma escrivaninha e deita com a cabeça encerrada nos travesseiros, voce tem vontade de ficar ali e nunca mais sair. Entretanto voce sente um odor de podridão e então se dá conta que o seu suvaco.\n')
                                    esc8 = input('O que voce vai fazer?\n1)Tomar um banho.\n2)Permanecer como está e ir dormir.\nResposta: ')
                                    if esc8 == '1':
                                        print('\nVoce percebe que sua mente esá agitada demais ,entao sobre isso enquanto se dirige ao banheiro.\n\nApós limpar a mente com uma boa ducha, voce escuta seu celular apitar diversas vezes... É sua mãe perguntando se está tudo bem, dezenas da mesma mensagem.\n')
                                        esc9 = input('O que voce faz?\n1)Conta a verdade, afinal, voce confia em sua mãe.\n2)Fala que está tudo bem, já que voe não tem intimidade com ela, mesmo ela sendo sua mãe.\nResposta: ')

                                        if esc9 == '1':
                                            print("\nVoce decide ligar para sua mãe para contar o que aconteceu e antes que ela pudesse ao menos dizer 'Alo?', voce despejou tudo aquilo que estava entalado na sua garganta.\n Mas após todo o seu desabafo, a sua mãe disse:'Mas filho, eu estou preocupada por causa das bombas que estão lançando por todo o mundo. Por enquanto aqui no Brasil não fomos atingidos, mas ficamos sabendo que a Itália, Grécia , Turquia , Alemanha Ocidental , Alemanha Oriental , Alasca , e outras pequenos destritos  da URSS seriam bombardeadas e por isso queria saber como voce está e para dizer que eu quero que voce pegue o primeiro v--...\n\n E antes que mais uma palavra sequer fosse dita, todo o prédio do dormitório explodiu. Seu quarto ficava no quarto e ultimo andar e por isso foi o primeiro a ser atingido mas voce não foi ferida... Poeira, destroços, tudo era um grande borrão em sua mente.\n ")
                                            esc10 = input('O que voce faz?\n1)Grita por socorro\n2)Tenta sair sozinha dos destroços.\nResposta: ')
                                            
                                            if esc10 == '1':
                                                print('\nVocê grita por socorro com todas as suas forças, clama por ajuda desesperadamente até que ouve alguém dizer seu nome ao longe \n(Gustavo)..\n..(Gustavo)..\n..(Gustavo)..\nVocê chama a atenção daquela voz para si, e em alguns instantes você vê Susan sobre si, com uma cara de desesperada ela tenta retirar os destroços de cima de você enquanto pergunta se você está bem e enquanto fala que estava preocupadissima. \nAo retirar o que ela consegui , ao ponto de voce poder retirar e mover alguns destroços por conta propria que lhe impedia de se mexer, ela te abraçou e enquanto te consolava dizendo que tudo ficaria bem. Vocês saem do prédio destruído, diversas vozes pediam por ajuda, cheiro de queimado e de poeira molhada enchiam todos os sentidos.\n ')
                                                esc11 = input('O que voce faz?\n1)Procurar um local mais seguro , para se ouver outros bombardeios\n2) tentar ajudar outras pessoas \nResposta: ')

                                                if esc11 == '1':
                                                    print('\nVocê diz que vai procurar um canto para se proteger se ouver outros ataques. \nVocê ve que a certa duvida nos olhos de Susan , e que talvez ele gostaria que da forma que ela te ajudou ela gostaria de tentar ajudar outros , porem ela concorda com voce e lhe segue.\n')
                                                    esc12 = input('Voce tem certeza de que vai abandonar todas aquelas pessoas feridas ?\n1)Sim\n2)Não\nResposta: ')
                                                    
                                                    if esc12 == '1':
                                                        print('\nVocê está decidido, Susan vai ter de aceitar , ja que ela sozinha nao consegue fazer muita coisa , entao ela engole o choro e lhe segue.\n.você caminha pelo campus todo destruido e ve que a horas atraz nem imaginava que isso poderia se quer ocorrer , voce ve corpos ja mortos e ve destruiçao em todo lado .\nVocê ve uma menina caída embaixo de uma escada(ou oque sobrou de um predio), a perna dela estava totalmente quebrada em ângulos sobrenaturais e ela chorava dor.VOce esta a uma distancia de 5 Metros dela , e se depara com uma questao , voce ve que o predio esta para desabar , e que um esforço muito grande nas vigas que sustentao o pedaço de escada onde a menina esta enterrada poderia fazer com que a contruçao inteira desabace , matando a menina e voce junto , mas voce nao se consideira um monstro tao grande ao ponto de abandonar a menina desesperada , de tanta dor , e olha para Susan e ve a cara de horror dela , e como ela esta com uma vontade de vomitar em ver todos aqueles cadaveres e pessoas gritando de desespero e agonia.\n')
                                                        esc13 = input('Você sabe que não conseguirá tirar a menina antes que a escada desabe. O que voce faz?\n1)Da o seu ,melhor para noa morrer e tirar a menina da escada \n2)Ignorar e fingir que nem vio a menina , se remoendo de dor \nResposta: ')

                                                        if esc13 == '1':
                                                            print('\nVocê não vai abandoná-la, como você viveria sabendo que abandonou um ser humano para a morte? Você junta todas as suas forças e pega aquela menina, ela grita com a dor, você não é nenhum medico, mas achava que ela tinha quebrado algumas costelas. Ao colocá-la nos braços, seus pés já estão em movimento, você corre...\ntenta sair dalí...\n...e por pouco você consegue com a escada desabando no exato momento em que você sai debaixo dela.\nVocê respira aliviada...\n\n\nUM CLARÃO SEGUIDO DE UM SOM ESTRONDOSO...\n\n\n\nVocê consegue se mexer e ao olhar para baixo percebe que suas pernas não estão mais lá, a menina que estava em seus braços está destroçada em seu peito...\nSua respiração começa a ficar mais lenta...\nSeus olhos ficam pesados...\nVocê tem um último pensamento enquanto sua mente fica nublada:"Por que?"')

                                                        elif esc13 == '2':
                                                           print('Mesmo toda a sua alma dizendo que aquilo é errado, no fundo seu único desejo é sobreviver. Você pede desculpas para aquela pobre garota que te olha suplicante para que não a deixe, mas você apenas se vira e começa a correr para longe dali.\nSeus olhos se enchem de lágrimas, você não consegue entender porque tomou uma atitude tão absurda. Ao olhar para trás, a escada imediatamente cai, devorando a pobre garota num turbilhão de poeira, você não aguenta ficar ali, corre desesperado, mas antes que qualquer pensamento seu se completasse...\nUM CLARÃO SEGUIDO DE UM SOM ESTRONDOSO...\nvoce por um segundo pensa em Susan , e como gostava dela , pensa em sua mae q como se arrepende de todas as suas açoes , e pensa "QUE DROGA EU FIZ DA MINHA VIDA" \nSua cabeça começa a girar e subitamente, antes que qualquer coisa passasse pela sua cabeça, tudo escureceu.')
                                                    
                                                    elif esc12 == '2':
                                                        print('Você volta atrás na sua decisão e pensa mais calmamente, pensa que poderia ajudar as pessoas. Ao olhar em volta percebe que ela(Susan) te levou pra uma praça bastante iluminada e que também possuia diversas pessoas feridas por lá e que havia gente vestida de branco correndo para elas, demorou mas você entendeu que eram médicos socorrendo quem precisasse. De repente uma dessas pessoas chega próximo a você e pergunta se você quer ajuda e para de repente meio espantado, você demora um pouco para perceber mas quem está a sua frente é Arthur te olhando com um olhar preocupado.\n')
                                                        esc13_1 = input('O que você faz?\n1)Pergunta o que ele está fazendo ali.\n2)Diz que está bem e que ele não precisa se preocupar.\nResposta: ')

                                                        if esc13_1 == '1':
                                                            print('Você fica confuso com o fato de Arthur estar naquele meio de gente e então você pergunta o que danado ele estava fazendo ali. Ele dá uma risadinha e diz que havia feito enfermagem antes de ir para Psicologia, ele começa a analisar seus ferimentos e declara que não há sinais de fraturas e nem de hemorragia interna. Após essa rápida checagem ele pergunta se você quer ir ao shopping perto dali que estava recebendo os atingidos pelas bombas.\n ')
                                                            esc14 = input('O que você faz?\n1)Prefere ir ao shopping.\n2)Decide ficar e esperar por Susan.\nResposta: ')
                                                            if esc14 == '1':
                                                                print('Ao olhar para ambos os lados e ver pessoas sangrando por todos os lados com visceras espalhados pelo chão você decide que aquele não seria um bom local para permanecer e pergunta em que direção fica o shopping. Arthur então pareceu um pouco irritado e perguntou se você não gostaria que ele te levasse até lá para a proteger, você ficou imaginando como um nanico como ele a protegeria, mas você guardou esse comentário para si. Você o perguntou de que ele te protegeria, e ele então já com a cara bem vermelha de raiva disse que muita gente podia se aproveitar de uma situação difícil como aquela para fazer maldades.\n ')
                                                                esc15 = input('O que você decide?\n1)Permite que ele te acompanhe.\n2)Agradece a intenção mas diz que pode se cuidar sozinho.\nResposta: ')

                                                                if esc15 == '1':
                                                                    print('Você pensa com cuidado e acaba permitindo que ele te acompanhe, embora alguma coisa pareça muito errada...\nVocê e Arthur então começam a caminhar para longe daquela praça, mas aquele caminho era muito estranho, os postes estavam todos quebrados e não há ninguém por lá, você então pergunta a Arthur se aquele caminho era seguro e ele apenas deu um sorriso sinistro dizendo que estava tudo bem já que ele estava lá.\nApós percorrer mais dez minutos, você percebe que o caminho começa a ficar de terra e mal-iluminado e então Arthur para diante de você - por todo o caminho ele andou em sua frente - e começou a rir, então com uma voz sinistra ele falou "Voces Filhinhos de papai nao sabem que nao devem confiar em estrnhos noa ? (risos)" e voltou a rir. Arthur então começou a se aproximar de você enquanto sacava algo de seu bolso .. uma enorme faca de caça brilhava em sua mão .. \n')
                                                                    esc16 = input('O que você faz?\n1)Fica parada pois não consegue se mexer.\n2)Se vira e corre para longe.\nResposta: ')
                                                                    if esc16 == '1':
                                                                        print('\nVocê não consegue se mover, sua mente simplesmente não consegue entender como alguém que parecia tão bondoso como Arthur fosse andar com uma faca e ainda mais falar aquele tipo de coisa. Ele se aproxima mais e pergunta se você não vai fugir, você não responde por medo e a cara dele começa a ficar vermelha de raiva e então ele começa a te insultar em russo, você podia não entender, mas sabia que com aquele tom ele só poderia estar lhe chamando de puta e mandando você se foder. Por um longo momento você fica observando assustada ele vociferar aquelas palavras, até que ele começa a se acalmar, ele guarda a faca e então fala que não tem graça brincar com quem não foge dele e vai embora desaparecendo na escuridão a frente de você.\n')
                                                                        esc17 = input('O que você faz?\n1)Senta e começa a chorar.\n2)Volta correndo para a praça.\nResposta: ')
                                                                        if esc17 == '1':
                                                                            print('Tudo aquilo foi demais para você. Você desaba no chão e começa a chorar, sem ligar para mais nada. Na sua mente uma única pergunta passava na sua cabeça era por que tudo aquilo estava acontecendo na sua vida, você tinha uma vaga numa das melhores universidades de todo o Canada, tinha finalmente sua independencia, tinha um lugar só seu e tinha sonhos a serem conquistados. Você abaixou sua cabeça e começou a choramingar baixinho repetindo "por que?" diversas vezes...\n\ne esse foi seu último pensamento antes que você sentisse algo frio entrando atrás do seu pescoço e então escuridão.\n')

                                                                        elif esc17 == '2':
                                                                            print('\nTudo aquilo foi demais para você, mas esperar que ele voltasse isso você não faria. Você então voltou correndo para a praça onde voce a via visto Susan pela ultima vez , aquela corrida pareceu que demorou um século, mas enfim você chegou na praça e correu os olhos buscando ela ,e talvez alguem para lhe consolar, e lá estava ela, ela estava totalmente coberta de poeira, você correu chorando para ela mas ela não pareceu te notar, até que você chegou mais perto e entendeu tudo.\nOs olhos de Susan estavam aberto mas não se moviam, seus ouvidos estavam cheios de sangue e ela não respondia a nenhum estímulo... susan tinha ficado cega e surda... você se vira para uma enfermeira e pergunta o que aconteceu, ela então explica que um novo bombardeio atingiu o local em que ele estava ajudando, mas que pelo fato de ela estar mais afastada levando mais alguém a bomba não a matou, mas lhe tirou os sentidos da visão e da audição.\n\nOito anos se passaram desde aquele dia horrível, você voltou ao Brasil e trouxe consigo Susan que agora não conseguia mais ser independente. Sua vida não era bem o que você queria, mas ao menos você sobreviveu e por isso agradece aos céus pela oportunidade de estar vivo.\n')
                                                                    
                                                                    elif esc16 == '2':
                                                                        print('\nAo ver a faca na mão daquele louco sua reação não é outra que não se virar e começar a correr em direção a praça. Você se virar e começa a correr até que escuta uma gargalhada estrondosa vinda de Arthur logo atrás de você, ele repetia consigo mesmo enquanto parecia estar extremamente excitado "isso mesmo, assim que eu gosto "suka"" e então ele disparou atrás de você, embora pequeno, ele conseguia bastante rápido e alcançou em instantes. Ele então pula em suas costas tal qual um gato atrás de um pequeno pardal e dá a primeira apunhalada, você cai com a dor e começa a gritar enquanto ele apenas ria da situação, ele se aproxima mais e então te dá outra facada, só que agora no seu peito. Seu sangue quente escorre pelo seu peito e ele ao perceber que você está prestes a perder a consciência começa a te furar cada vez mais, você o olha nos olhos e tudo o que vê é um animal... e essa foi a última coisa que seus olhos puderam ver.\n')
                                                                
                                                                elif esc15 == '2':
                                                                    print('\nVocê agradece a intenção de Arthur mas fala que pode muito bem se cuidar sozinho e que não imagina quem poderia se aproveitar de uma situação de crise como aquela, mas ele apenas só sorri maliciosamente para você e sai de perto. Aquilo foi bem estranho, mas isso não te abalou e você foi perguntar a outra pessoa onde ficava o shopping que estava recebendo os desabrigados. Você avistou uma mulher e foi questioná-la sobre o local, e ela apenas lhe olhou surpresa e perguntou quem havia te dito uma mentira tão descarada como essa, a mulher explicou então que toda a cidade estava destruída, apenas alguns locais abertos como aquela praça ainda estavam intactos.\nVocê espera então por um momento junto daquela mulher que tratava os feridos, mesmo estando totalmente enojado com a situação. Um zumbido então toma o ar e você algo indo direto para onde Susan se encontrava.\n ')
                                                                    esc16_1 = input('O que você faz?\n1)Corre para avisar Susan\n2)Espera com aquela mulher.\nResposta: ')

                                                                    if esc16_1 == '1': 
                                                                        print('\nVocê não pensa duas vezes e começa a correr para onde Susan te resgatou gritando seu nome desesperadamente.\n Você corre por meio de imensas arvores que não lembra de ter passado ali, até que vê ela, heroicamente ajudando alguém em seus braços, você apressa seus passos, mas o destino é cruel... Uma das bombas atinge a praça perto de onde vocês estão e então... CLARÃO...SOM DE ARVORE CAINDO... e de repente... uma escuridão total.\n')
                                                                    
                                                                    elif esc16_1 == '2':
                                                                        print('\nVocê continua a olhar apreensivamente para os céus e então pergunta a mulher ao seu lado o que você deveria fazer, "fique AQUI" disse ela num tom sério também olhando para os céus e de repente um clarão não tão longe quase os cegou. Um bombardeio atingiu justamente o local em que susan estava, você se levanta para correr em busca dele, mas a mulher ao seu lado te puxa e aponta para o céu, diversos aviões estão lançando mísseis justamente nos aviões que bombardearam sua pobre e linda Susan, destroços começam a cair do céu, e caem justamente em um monte de arvores, derrubando-as. Seu coração não tem mais esperança...\n\nOito anos depois você está de volta ao Brasil, conseguiu terminar seus estudos e publicou um livro de muito sucesso sobre a guerra em que sobreviveu, sua vida foi pacata e feliz desde então...\n')
                                                                elif esc14 == '2':
                                                                    print("")

                                                elif esc11 == '2':
                                                    print('\n Voce e Susan se dirigem para um canto onde podem procurar mais informaçoes sobre como podem ajuda. Era um lugar amplo e bem iluminado, uma praça onde diversas pessoas continuavam chegando e outras corriam para elas com maletas e luvas nas mãos.\nEnquanto tentava esquadrinhar o local, um rapaz ruivo se aproximou de você com a mesma aparência daqueles que ajudavam quem ali chegava e perguntou se ele poderia te examinar, já tirando da maleta um estetoscópio.\n')
                                                    esc_12 = input("O que você faz?\n1)Permite que ele te examine\n2)Diz que não precisa e que você está se sentindo bem\nResposta: ")

                                                    if esc_12 == '1':
                                                        print('\nVocê diz que pode sim, então ele se agacha em frente a voce, pede licença e coloca o estetoscópio em seu peito,Ele termina de te checar e fala que está tudo normal, e sugere que você se junte a um grupo de pessoas pois naquele momento muita gente estranha poderia querer se aproveitar dos feridos.\n')
                                                        esc_13 = input('Qual a sua decisão?\n1)')

                                                    
                                                    elif esc_12 =='2':
                                                        print("")
            elif esc2 == '2':
                print('')

        elif esc1 == '2':
            print('')

    elif esc == '2':
        print('Voce PERDEU seu primeiro dia de aula, e morre quando uma bomba atinge inesperadamente o dormitório onde voce foi procurar refúgio após ter se acorvadado.\n')
					
